export * from './scholarships-response.interface'
export * from './scholarship.interface'
export * from './postulation-response.interface'
export * from './requirements-response.interface'
export * from './requirement.interface'
export * from './input-model.interface'
export * from './upload-response.interface'
export * from './citizen.interface'
